import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import UploadImage from "../components/UploadImage";
import Result from "../components/Result";
import Footer from "../components/Footer";
import {useState} from "react";

type Res = {
  predict:string,
  value:number
}
export default function Home() {

  const [name, setName] = useState('Esperando imágen...')
  const [value, setValue] = useState('')
  const predictName = async (res:Res) => {
    await setName(res.predict);
    await setValue(""+res.value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <UploadImage predictedValue={predictName}/>
        <Result name={name} value={value}/>
        <Footer/>
      </main>
    </div>
  )
}
